# Generated by Django 3.0.3 on 2020-03-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0037_auto_20200327_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Student_email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
    ]
