# Generated by Django 3.0.3 on 2020-03-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0038_exam_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Time_start',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='Time_stop',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam_results',
            name='Time_stop',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
