# Generated by Django 3.0.3 on 2020-03-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0039_auto_20200329_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Course_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
