# Generated by Django 3.0.3 on 2020-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0040_exam_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_registration',
            name='Contact_email',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_registration',
            name='Contact_message',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_registration',
            name='Contact_name',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
