# Generated by Django 3.0.3 on 2020-03-30 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0041_auto_20200330_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_registration',
            name='Contact_email',
        ),
        migrations.RemoveField(
            model_name='admin_registration',
            name='Contact_message',
        ),
        migrations.RemoveField(
            model_name='admin_registration',
            name='Contact_name',
        ),
    ]
