# Generated by Django 3.0.3 on 2020-03-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0042_auto_20200330_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_name', models.CharField(max_length=200)),
                ('Contact_email', models.EmailField(max_length=200)),
                ('Contact_message', models.TextField()),
            ],
        ),
    ]
