# Generated by Django 3.0.3 on 2020-03-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0043_guest_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Approval_status',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
