# Generated by Django 3.0.3 on 2020-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0050_remove_exam_results_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Lock',
            field=models.CharField(max_length=200),
            preserve_default=False,
        ),
    ]
