# Generated by Django 3.0.3 on 2020-04-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0051_exam_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Paid_amount',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
