# Generated by Django 3.0.3 on 2020-04-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0052_enrollment_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_chapter_content',
            name='Text_content',
            field=models.TextField(default='Nil'),
        ),
    ]
