# Generated by Django 3.0.3 on 2020-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0056_review_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_progress',
            name='Course_chapter_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
