# Generated by Django 3.0.6 on 2020-05-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0057_learning_progress_course_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Course_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Subject_name',
            field=models.TextField(),
        ),
    ]
